seed: 42

num_workers: 8
experiment_name: "Baseline"

dataset_root: "YOUR_PATH_TO_DATASET"
# The dataset contains mapping images and mri images that are used to create the mapping images.
# These configs determine which images to use for testing and valindation: only mapping images or all (including mappings)
val_mapping_only: True 
test_mapping_only: True

trainer:
  gpus: 1
  max_epochs: 150
  mapping_only_epochs: 50 # In the last mapping_only_epochs only train on mapping images (transition at max_epochs - mapping_only_epochs)
  benchmark: True
  precision: 16
  gradient_clip_val: 5.0
#  resume_from_checkpoint: 2020-10-30/epoch=67.ckpt

model:
  encoder_name: "tu-resnet50"
  encoder_weights: "imagenet"
  freeze_encoder_weights_epochs: 0

# scheduler:
#   type: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
#   T_0: 10
#   T_mult: 2
scheduler:
  gamma: 0.1
  step_size: 50
  type: torch.optim.lr_scheduler.StepLR

loss: "JaccardLoss"

batch_size: 64

optimizer:
  type: torch.optim.Adam
  lr: 0.0001